name: build

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build-linux:
    runs-on: nix-builder
    strategy:
      fail-fast: false
      matrix:
        package:
          - default
          - neovim
    steps:
      - uses: actions/checkout@v6

      - name: build and push
        run: |
          nix run github:zhaofengli/attic#default -- \
            login cache https://cache.rudesome.nl ${{ secrets.ATTIC_TOKEN }}
          nix run github:zhaofengli/attic#default -- watch-store cache &
          WATCH_PID=$!
          nix build '.#packages.x86_64-linux.${{ matrix.package }}'
          nix run github:zhaofengli/attic#default -- push cache result -j 2
          kill $WATCH_PID || true

  build-darwin:
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        package:
          - default
          - neovim
    steps:
      - uses: actions/checkout@v6

      - name: Raise file descriptor limit
        run: |
          sudo launchctl limit maxfiles 524288 524288 || true
          ulimit -n 524288 || true

      - uses: DeterminateSystems/nix-installer-action@main
        with:
          extra-conf: |
            fallback = true
            http-connections = 128
            max-substitution-jobs = 128
            extra-substituters = https://nix-community.cachix.org?priority=42
            extra-trusted-public-keys = nix-community.cachix.org-1:mB9FSh9qf2dCimDSUo8Zy7bkq5CX+/rkCWyvRCYg3Fs=

      - name: Setup Attic cache
        uses: ryanccn/attic-action@v0
        with:
          endpoint: https://cache.rudesome.nl/
          cache: cache
          token: ${{ secrets.ATTIC_TOKEN }}

      - name: build
        run: |
          ulimit -n 524288 || true
          nix build '.#packages.aarch64-darwin.${{ matrix.package }}'
          nix run github:zhaofengli/attic#default -- push cache result -j 2
