name: flake

on:
  pull_request:
    branches:
      - master

jobs:
  check:
    runs-on: nix-builder
    env:
      NIX_CONFIG: |
        extra-substituters = https://cache.rudesome.nl/cache?priority=41 https://nix-community.cachix.org?priority=42
        extra-trusted-public-keys = cache:uz+4bhhavVggsidftGM12+XGcuWdaFM1/ou1w5whovc= nix-community.cachix.org-1:mB9FSh9qf2dCimDSUo8Zy7bkq5CX+/rkCWyvRCYg3Fs=
    steps:
      - uses: actions/checkout@v6
      - name: flake check all systems
        run: nix flake check --all-systems
